### ISSUE TITLE
BetterHudLite: DLC2 Seeker's abilty "Meditate" is covered by the hud

### ISSUE THREAD

**Issue by LassePladsen** [TheTimeSweeper/WagaTamashiiWaMadaMoeteOru#6]
Seeker's special ability "meditate" has a quick-time sort of event where you press buttons shown on the screen (sort of like Helldivers 2), but these buttons are covered by the hud which is moved to the middle of the screen in BetterHudLite

**Comment by TheTimeSweeper** [comment]
fixed
